[build]
  base = "/"
  publish = "public"
  command = "gatsby clean && gatsby build"

[build.environment]
  NODE_VERSION = "14.15.0"
  YARN_VERSION = "1.22.17"
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[plugins]]
  package = "./netlify/plugin"
