local_backend:
    url: http://localhost:8081/api/v1
    allowed_hosts: ['192.168.0.1']


backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

# Uncomment local_backend when you need to develop in your local
#local_backend: true # run `npx netlify-cms-proxy-server` for local testing

media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI
    label_singular: "Post" # Used in the UI, ie: "New Post"
    description: >
      Create awesome content here.
    folder: "src/content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} — {{year}}/{{month}}/{{day}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Template",
          name: "template",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          hint: "Start slug with /. Use only alphanumeric characters, - and _. Avoid spaces in any cases.",
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - { label: "SEO Description", name: "description", widget: "text" }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: "image",
          required: false,
          tagname: "",
        }

      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          hint: "Main content goes here.",
        }

  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/index.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "index-page",
            }
          - label: "Header Slides"
            name: "header_slides"
            label_singular: 'Header Slide'
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - { label: "Paragraph", name: "excerpt", widget: "markdown" }
              - { label: 'Header Image', name: 'header_image', widget: 'image', required: true }
              - label: "CTA"
                name: "cta"
                widget: "object"
                fields:
                  - name: "ctaType"
                    label: "CTA type"
                    widget: "select"
                    options: ["button", "search bar", "none"]
                  - name: "ctaText"
                    label: "CTA text (For button CTA type)"
                    widget: "string"
                  - name: "ctaLink"
                    label: "CTA Link (For button CTA type)"
                    widget: "string"

          - label: 'Section 1 (Title and Paragraph)'
            name: section1
            widget: 'object'
            fields:
              - {
                  label: 'ID',
                  name: 'id',
                  widget: string
                }
              - {
                  label: 'Title',
                  name: section1_title,
                  widget: string
                }
              - {
                  label: 'Paragraph',
                  name: section1_paragraph,
                  widget: markdown,
                }
              - {
                  label: 'Button',
                  name: btn,
                  widget: boolean,
                  default: false
                }
              - {
                  label: 'Button Text',
                  name: btn_text,
                  widget: string,
                }
              - {
                  label: 'Button type',
                  name: btn_type,
                  widget: select,
                  options: [{ label: "White", value: "button-secondary" }, { label: "Orange", value: "button-primary" }]
                }

          # - label: 'Slider Section 1'
          #   name: slider1
          #   widget: 'object'
          #   fields:
          #     - {
          #         label: 'Title',
          #         name: section1_title,
          #         widget: string
          #       }
          #     - {
          #         label: 'Paragraph',
          #         name: section1_paragraph,
          #         widget: string,
          #       }


      - label: "About"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/about" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "src/content/pages/contact.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "contact-page",
            }
          - {
              label: "Slug",
              name: "slug",
              widget: "hidden",
              default: "/contact",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }


  - name: "slider_cards"
    label: "Slider Cards"
    label_singular: "Slider Card"
    description: >
      Create a slider card here.
    folder: "src/content/cards"
    create: true
    fields:
      - {
          label: "Card Type",
          name: "card_type",
          widget: "select",
          default: "Article White",
          options: ['Article White', 'Article Green', 'Article List', 'Video Card', 'Audio Card']
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "text", required: true }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: "image",
          required: false,
        }
      - {
          label: "Resource Links",
          name: "resources",
          widget: "list",
          hint: "List URL for resource links here (For Article List card only)",
        }
      - {
          label: "Video Source",
          name: "video",
          widget: "string",
          hint: "Provide embed URL for video link here (For Video Card only)",
        }
      - {
          label: "Audio Source",
          name: "audio",
          widget: "string",
          hint: "Provide embed URL for audio link here (For Audio Card only)",
        }

  - name: settings
    label: Settings
    files:
      - name: general
        label: General
        file: "src/util/site.json"
        fields:
          - label: meta
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Site Title
                required: true
              - widget: string
                name: titleTemplate
                label: Title Template
                default: "%s"
                required: true
              - widget: string
                name: siteUrl
                label: Website URL
                required: true
              - widget: text
                name: description
                label: Description
                default: ""
                required: false
              - widget: image
                name: image
                label: image
                default: "/assets/stackrole.png"
              - widget: image
                name: iconimage
                label: favicon
              - widget: string
                name: twitterUsername
                label: Twitter
                required: false

          - label: "Google Analytics"
            name: ga
            widget: string
            hint: "Add you tracking ID, for example UA-XXXXXXXXX-X"
      - label: Social Icons
        name: socialIcons
        file: "src/util/socialmedia.json"
        fields:
          - label: Social Icons
            name: socialIcons
            widget: list
            collapsed: true
            hint: "Here you can add social icons, Click on 'Add social icons'"
            fields:
              - label: "Icons"
                name: "icon"
                widget: "select"
                options:
                  [
                    "facebook",
                    "twitter",
                    "linkedin",
                    "youtube",
                    "instagram",
                    "rss",
                    "github",
                    "telegram",
                    "pinterest",
                    "snapchat",
                    "skype",
                    "wordpress",
                    "tiktok",
                    "dribbble",
                    "medium",
                    "behance",
                    "vk",
                  ]
                hint: "Select the Icon"
              - widget: string
                name: url
                label: url
                required: true
                hint: "Paste the 'URL' of your Social media"

  - label: "Appearance"
    name: "appearance"
    identifier_field: "name"
    files:
      - label: "Default Theme"
        name: "themescolors"
        file: "src/util/default-colors.json"
        fields:
          - label: "Primary Color"
            name: "siteColor"
            widget: "color"
            enableAlpha: true
            allowInput: true
      - label: "Dark Theme"
        name: "darkthemescolors"
        file: "src/util/dark-theme-colors.json"
        fields:
          - label: "Primary Color"
            name: "siteColor"
            widget: "color"
            enableAlpha: true
            allowInput: true
